# Generated by Django 5.2.7 on 2025-10-21 15:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('mentee', 'Mentee'), ('mentor', 'Mentor'), ('head', 'Head of Mentor Mentee')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HeadofMentorMentee',
            fields=[
                ('HeadofMentorMenteeID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('HeadofMentorMenteeName', models.CharField(max_length=100)),
                ('HeadofMentorMenteeEmail', models.EmailField(max_length=254)),
                ('HeadofMentorMenteePhone', models.CharField(max_length=15)),
                ('HeadofMentorMenteeIC', models.CharField(max_length=15)),
                ('HeadofMentorMenteeAddress', models.CharField(max_length=255)),
                ('HeadofMentorMenteePostcode', models.CharField(max_length=10)),
                ('HeadofMentorMenteeCity', models.CharField(max_length=50)),
                ('HeadofMentorMenteeState', models.CharField(max_length=50)),
                ('HeadofMentorMenteeRace', models.CharField(max_length=50)),
                ('HeadofMentorMenteeReligion', models.CharField(max_length=50)),
                ('HeadofMentorMenteeDeparment', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('MenteeID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('MenteeName', models.CharField(max_length=100)),
                ('MenteeCourse', models.CharField(max_length=100)),
                ('MenteeSemester', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('MenteeJoinDate', models.DateField()),
                ('MenteeEmail', models.EmailField(max_length=254)),
                ('MenteePhone', models.CharField(max_length=15)),
                ('MenteeIC', models.CharField(max_length=15)),
                ('MenteeAddress', models.CharField(max_length=255)),
                ('MenteePostcode', models.CharField(max_length=10)),
                ('MenteeCity', models.CharField(max_length=50)),
                ('MenteeState', models.CharField(max_length=50)),
                ('MenteeRace', models.CharField(max_length=50)),
                ('MenteeReligion', models.CharField(max_length=50)),
                ('MenteePreviousSchool', models.CharField(max_length=100)),
                ('MenteeFatherName', models.CharField(max_length=100)),
                ('MenteeFatherIC', models.CharField(max_length=15)),
                ('MenteeFatherOccupation', models.CharField(max_length=100)),
                ('MenteeFatherPhone', models.CharField(max_length=15)),
                ('MenteeMotherName', models.CharField(max_length=100)),
                ('MenteeMotherIC', models.CharField(max_length=15)),
                ('MenteeMotherOccupation', models.CharField(max_length=100)),
                ('MenteeMotherPhone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('MentorID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('MentorName', models.CharField(max_length=100)),
                ('MentorEmail', models.EmailField(max_length=254)),
                ('MentorPhone', models.CharField(max_length=15)),
                ('MentorIC', models.CharField(max_length=15)),
                ('MentorAddress', models.CharField(max_length=255)),
                ('MentorPostcode', models.CharField(max_length=10)),
                ('MentorCity', models.CharField(max_length=50)),
                ('MentorState', models.CharField(max_length=50)),
                ('MentorRace', models.CharField(max_length=50)),
                ('MentorReligion', models.CharField(max_length=50)),
                ('MentorDeparment', models.CharField(max_length=100)),
                ('MaxMentees', models.IntegerField()),
                ('MentorJoinDate', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
