# Generated by Django 5.2.7 on 2025-10-21 17:38

import django.db.models.deletion
import system.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=system.models.user_profile_picture_path),
        ),
        migrations.AddField(
            model_name='mentee',
            name='MenteeGender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='mentee',
            name='MenteeStatus',
            field=models.CharField(choices=[('active', 'Continue Study'), ('inactive', 'Not Continuing'), ('graduated', 'Graduated')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='mentee',
            name='assigned_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.mentor'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='CurrentMentees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='MaxMentees',
            field=models.IntegerField(default=20),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('ActivityID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ActivityName', models.CharField(max_length=200)),
                ('ActivityType', models.CharField(choices=[('mentoring', 'Mentoring Session'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('meeting', 'Meeting'), ('other', 'Other')], max_length=20)),
                ('Description', models.TextField(blank=True)),
                ('Date', models.DateField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('Location', models.CharField(max_length=200)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('IsMentoringSession', models.BooleanField(default=False)),
                ('CreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='activity_reports/')),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.activity')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.mentee')),
            ],
            options={
                'unique_together': {('activity', 'mentee')},
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='Attendees',
            field=models.ManyToManyField(through='system.Attendance', to='system.mentee'),
        ),
        migrations.CreateModel(
            name='MentoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=20)),
                ('topic', models.CharField(max_length=200)),
                ('materials', models.FileField(blank=True, null=True, upload_to='session_materials/')),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.activity')),
            ],
        ),
    ]
