# Generated by Django 5.2.7 on 2025-10-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_customuser_profile_picture_mentee_menteegender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='attendance_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='present_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='total_attendees',
            field=models.IntegerField(default=0),
        ),
    ]
