# Generated by Django 5.2.7 on 2025-10-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_activityreport_attendance_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='MentorDeparment',
            new_name='MentorDepartment',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
