# Generated by Django 5.2.7 on 2025-10-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_rename_mentordeparment_mentor_mentordepartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
