# Generated by Django 5.2.7 on 2025-10-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_mentee_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headofmentormentee',
            old_name='HeadofMentorMenteeDeparment',
            new_name='HeadofMentorMenteeDepartment',
        ),
    ]
