# Generated by Django 5.2.7 on 2025-10-23 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_rename_headofmentormenteedeparment_headofmentormentee_headofmentormenteedepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual'), ('reassignment', 'Reassignment')], default='manual', max_length=20)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.mentor')),
            ],
            options={
                'ordering': ['-assigned_date'],
                'unique_together': {('mentee', 'mentor', 'is_active')},
            },
        ),
    ]
