# Generated by Django 5.2.7 on 2025-10-23 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_mentorassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorAssignment',
        ),
    ]
