# Generated by Django 5.2.7 on 2025-11-02 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_mentormenteeassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='Mentor',
        ),
        migrations.AddField(
            model_name='activity',
            name='AdditionalMentors',
            field=models.ManyToManyField(blank=True, related_name='additional_activities', to='system.mentor'),
        ),
        migrations.AddField(
            model_name='activity',
            name='PrimaryMentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_activities', to='system.mentor'),
        ),
    ]
