# Generated by Django 5.2.7 on 2025-11-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_remove_activity_mentor_activity_additionalmentors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='AcademicSupportNeeds',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='CurrentCGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='MenteeAcademicGoals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='MenteeExtracurricular',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='MenteeStudyHabits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='MenteeSubjects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Sem1ActualGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Sem1TargetGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Sem2ActualGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Sem2TargetGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Sem3ActualGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Sem3TargetGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Sem4ActualGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Sem4TargetGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Sem5ActualGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Sem5TargetGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Sem6ActualGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Sem6TargetGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='TargetCGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
