# Generated by Django 5.2.7 on 2025-11-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_mentee_academicsupportneeds_mentee_currentcgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='mentor_profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='mentee_profile_pictures/'),
        ),
    ]
